In [3]:
import GateGeneration as gg
import numpy as np
import MathematicaScripts as scripts

In [ ]:
#define Ising interactions needed
Jij_XX = np.array([[0, 0.5, 0.5, 0],
                   [0, 0, 0, 0.5],
                   [0, 0, 0, 0.5],
                   [0, 0, 0, 0]])
Jij_YY = Jij_XX

Jij_ZZ = np.array([[0, 1, 1, 1],
                   [0, 0, 1, 1],
                   [0, 0, 0, 1],
                   [0, 0, 0, 0]])

Jij_XY = np.array([[0, 0, 0, 0],
                   [0, 0, -0.5, 0],
                   [0, 0, 0, 0],
                   [0, 0, 0, 0]])

Jij_YX = np.array([[0, 0, 0, 0],
                   [0, 0, 0.5, 0],
                   [0, 0, 0, 0],
                   [0, 0, 0, 0]])




In [12]:
#get some trap data to work with
Vrf = 500
V = (12.6, -15.9, 1)
NIons = 4
# secular_frequencies = scripts.find_secular_frequencies("ren", NIons, Vrf, V)
# equil_positions = scripts.find_equilibrium_positions(NIons, secular_frequencies)
secular_frequencies = scripts.current_secular_frequencies("ren")
equil_positions = scripts.current_equilibrium_positions()
print("secular:", secular_frequencies)
print("equil:", equil_positions)
mode_frequencies, mode_vectors = gg.eigensystem(equil_positions, secular_frequencies, NIons)
print("mode vectors:", mode_vectors)

secular: [0.5661182  5.11117009 4.53510495]
equil: [[ 1.95559362e-05  0.00000000e+00  0.00000000e+00]
 [ 6.18443759e-06  0.00000000e+00  0.00000000e+00]
 [-6.18443759e-06  0.00000000e+00  0.00000000e+00]
 [-1.95559362e-05  0.00000000e+00  0.00000000e+00]]
mode vectors: [[ 0.5         0.5         0.5         0.5       ]
 [-0.67419681 -0.21321036  0.21321036  0.67419681]
 [-0.5         0.5         0.5        -0.5       ]
 [ 0.21321036 -0.67419681  0.67419681 -0.21321036]]


In [13]:
weights_XX = scripts.Jij_to_weights(Jij_XX, mode_vectors)
print("weights:", weights_XX)
weights_YY = scripts.Jij_to_weights(Jij_YY, mode_vectors)
print("weights:", weights_YY)
weights_ZZ = scripts.Jij_to_weights(Jij_ZZ, mode_vectors)
print("weights:", weights_ZZ)
weights_XY = scripts.Jij_to_weights(Jij_XY, mode_vectors)
print("weights:", weights_XY)
weights_YX = scripts.Jij_to_weights(Jij_YX, mode_vectors)
print("weights:", weights_YX)


found secular frequencies
weights: [0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.
 0.   0.  ]
found secular frequencies
weights: [0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.
 0.   0.  ]
found secular frequencies
weights: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
found secular frequencies
weights: [0.    0.    0.    0.125 0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.125 0.    0.125 0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.125 0.    0.    0.    0.   ]
found secular frequencies
weights: [0.125 0.125 0.    0.    0.    0.    0.    0.    0.    0.    0.125 0.125
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
